on: [push]
env:
  PYSRC: src
jobs:
  test:
    runs-on: docker
    container:
      image: node:current
    steps:
      - uses: actions/checkout@v6
      - name: Install python3-venv
        run: |
          apt update
          apt install -y python3-venv

      - name: Linting
        run: |
          ${{ env.FORGEJO_WORKSPACE }}/tests/lint.sh
