on: [push]
env:
  PYSRC: src
jobs:
  test:
    runs-on: docker
    container:
      image: node:current
    steps:
      - uses: actions/checkout@v6
      - name: Debug info
        run: |
          pwd
          env

      - name: Install python3-venv
        run: |
          apt update
          apt install -y python3-venv

      - name: Create and activate VENV and install deps
        run: |
          python3 -m venv ${{ env.HOME }}/.venv
          source ${{ env.HOME }}/.venv/bin/activate
          echo "PATH=$VIRTUAL_ENV/bin:$PATH" >> $GITHUB_ENV
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
          pip install -U pip mypy flake8 aiohttp
          mypy --install-types --non-interactive ${{ env.FORGEJO_WORKSPACE }}/${{ env.PYSRC }}

      - name: Linting
        run: |
          set -x
          mypy --disallow-untyped-defs ${{ env.FORGEJO_WORKSPACE }}/${{ env.PYSRC }}
          flake8 --max-line-length 120 ${{ env.FORGEJO_WORKSPACE }}/${{ env.PYSRC }}
